server:
  port: 9000
spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: inventory-service
              uri: lb://INVENTORY-SERVICE
              predicates:
                - Path=/api/v1/products/**
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/auth/**
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/api/v1/orders/**
            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/api/v1/payments/**



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${SPRING_SECURITY_USER_NAME}:${SPRING_SECURITY_USER_PASSWORD}@localhost:8761/eureka
  instance:
    prefer-ip-address: true


