spring.datasource.url=jdbc:postgresql://localhost:5432/user-db-e-test
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=1780c751e9e9c17044c0678a2c1c8be9bc948d3bab76056f29b00d202f60f4a7

eureka.client.service-url.defaultZone=http://admin:password@localhost:8761/eureka
eureka.instance.prefer-ip-address=true