spring.application.name=order-service

server.port=9002

spring.profiles.active=dev

product-service.url=lb://INVENTORY-SERVICE

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=order-service

gateway.service.name=API-GATEWAY

inventory.reserved.api=/api/v1/inventory/reserved

