spring.application.name=inventory-service

server.port=9001

spring.profiles.active=dev

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=inventory-service

gateway.service.name=API-GATEWAY

payment.api=/api/v1/payments